using System.Collections.Generic;

/// <summary>
/// Wire size of every server packet the server defines for its PACKETVER (20250716 on the
/// MixPandas UnityRO branch), generated by compiling a sizeof() probe against the server's own
/// src/map/packets.hpp + packets_struct.hpp. -1 marks packets that carry their int16 length
/// right after the header. Entries marked "(server packet table)" are variable-length packets
/// the server writes without a struct (e.g. ZC_NPC_CHAT), taken from its evaluated
/// clif_packetdb.hpp; fixed sizes from that table are left out because they can be stale.
///
/// PacketSerializer uses it to step over packets this client has no handler for instead of
/// dropping everything batched behind them (the desync the NEWER_PACKETVER region in
/// PacketHeader.cs describes). Regenerate if the server's PACKETVER changes.
/// </summary>
public static class KnownPacketSizes {

    public static readonly Dictionary<ushort, int> Sizes = new Dictionary<ushort, int> {
        { 0x0069, -1 }, // (server packet table)
        { 0x006b, -1 }, // (server packet table)
        { 0x0074, 3 }, // ZC_REFUSE_ENTER
        { 0x0075, -1 }, // (server packet table)
        { 0x007f, 6 }, // ZC_NOTIFY_TIME
        { 0x0080, 7 }, // ZC_NOTIFY_VANISH
        { 0x0081, 3 }, // SC_NOTIFY_BAN
        { 0x0087, 12 }, // ZC_NOTIFY_PLAYERMOVE
        { 0x0088, 10 }, // ZC_STOPMOVE
        { 0x008d, -1 }, // ZC_NOTIFY_CHAT
        { 0x008e, -1 }, // (server packet table)
        { 0x0091, 22 }, // ZC_NPCACK_MAPMOVE
        { 0x009a, -1 }, // ZC_BROADCAST
        { 0x009c, 9 }, // ZC_CHANGE_DIRECTION
        { 0x009d, 19 }, // ZC_ITEM_ENTRY
        { 0x00a1, 6 }, // ZC_ITEM_DISAPPEAR
        { 0x00ae, -1 }, // (server packet table)
        { 0x00af, 6 }, // ZC_ITEM_THROW_ACK
        { 0x00b0, 8 }, // ZC_PAR_CHANGE
        { 0x00b1, 8 }, // ZC_LONGPAR_CHANGE
        { 0x00b3, 3 }, // ZC_RESTART_ACK
        { 0x00b4, -1 }, // ZC_SAY_DIALOG
        { 0x00b5, 6 }, // ZC_WAIT_DIALOG
        { 0x00b6, 6 }, // ZC_CLOSE_DIALOG
        { 0x00b7, -1 }, // ZC_MENU_LIST
        { 0x00bc, 6 }, // ZC_STATUS_CHANGE_ACK
        { 0x00bd, 44 }, // ZC_STATUS
        { 0x00be, 5 }, // ZC_STATUS_CHANGE
        { 0x00c0, 7 }, // ZC_EMOTION
        { 0x00c2, 6 }, // ZC_USER_COUNT
        { 0x00c4, 6 }, // ZC_SELECT_DEALTYPE
        { 0x00c6, -1 }, // (server packet table)
        { 0x00c7, -1 }, // ZC_PC_SELL_ITEMLIST
        { 0x00ca, 3 }, // ZC_PC_PURCHASE_RESULT
        { 0x00d1, 4 }, // ZC_SETTING_WHISPER_PC
        { 0x00d2, 4 }, // ZC_SETTING_WHISPER_STATE
        { 0x00d4, -1 }, // ZC_WHISPER_LIST
        { 0x00d6, 3 }, // ZC_ACK_CREATE_CHATROOM
        { 0x00d7, -1 }, // ZC_ROOM_NEWENTRY
        { 0x00d8, 6 }, // ZC_DESTROY_ROOM
        { 0x00da, 3 }, // ZC_REFUSE_ENTER_ROOM
        { 0x00db, -1 }, // ZC_ENTER_ROOM
        { 0x00dc, 28 }, // ZC_MEMBER_NEWENTRY
        { 0x00dd, 29 }, // ZC_MEMBER_EXIT
        { 0x00df, -1 }, // ZC_CHANGE_CHATROOM
        { 0x00e1, 30 }, // ZC_ROLE_CHANGE
        { 0x00ea, 5 }, // ZC_ACK_ADD_EXCHANGE_ITEM
        { 0x00ec, 3 }, // ZC_CONCLUDE_EXCHANGE_ITEM
        { 0x00ee, 2 }, // ZC_CANCEL_EXCHANGE_ITEM
        { 0x00f0, 3 }, // ZC_EXEC_EXCHANGE_ITEM
        { 0x00f1, 2 }, // ZC_EXCHANGEITEM_UNDO
        { 0x00f2, 6 }, // ZC_NOTIFY_STOREITEM_COUNTINFO
        { 0x00f6, 8 }, // ZC_DELETE_ITEM_FROM_STORE
        { 0x00f8, 2 }, // ZC_CLOSE_STORE
        { 0x00fa, 3 }, // ZC_ACK_MAKE_GROUP
        { 0x00fb, -1 }, // (server packet table)
        { 0x0105, 31 }, // ZC_DELETE_MEMBER_FROM_GROUP
        { 0x0107, 10 }, // ZC_NOTIFY_POSITION_TO_GROUPM
        { 0x0109, -1 }, // ZC_NOTIFY_CHAT_PARTY
        { 0x010a, 6 }, // ZC_MVP_GETTING_ITEM
        { 0x010b, 6 }, // ZC_MVP_GETTING_SPECIAL_EXP
        { 0x010c, 6 }, // ZC_MVP
        { 0x010d, 2 }, // ZC_THROW_MVPITEM
        { 0x010e, 11 }, // ZC_SKILLINFO_UPDATE
        { 0x010f, -1 }, // ZC_SKILLINFO_LIST
        { 0x0110, 14 }, // ZC_ACK_TOUSESKILL
        { 0x0111, 39 }, // ZC_ADD_SKILL
        { 0x0115, 35 }, // ZC_NOTIFY_SKILL_POSITION
        { 0x0117, 18 }, // ZC_NOTIFY_GROUNDSKILL
        { 0x011e, 3 }, // ZC_ACK_REMEMBER_WARPPOINT
        { 0x0120, 6 }, // ZC_SKILL_DISAPPEAR
        { 0x0121, 14 }, // ZC_NOTIFY_CARTITEM_COUNTINFO
        { 0x0125, 8 }, // ZC_DELETE_ITEM_FROM_CART
        { 0x012b, 2 }, // ZC_CARTOFF
        { 0x012c, 3 }, // ZC_ACK_ADDITEM_TO_CART/cart_additem_ack
        { 0x012d, 4 }, // ZC_OPENSTORE
        { 0x0131, 86 }, // ZC_STORE_ENTRY
        { 0x0132, 6 }, // ZC_DISAPPEAR_ENTRY
        { 0x0135, 7 }, // ZC_PC_PURCHASE_RESULT_FROMMC
        { 0x0139, 16 }, // ZC_ATTACK_FAILURE_FOR_DISTANCE
        { 0x013a, 4 }, // ZC_ATTACK_RANGE
        { 0x013b, 4 }, // ZC_ACTION_FAILURE
        { 0x013c, 4 }, // ZC_EQUIP_ARROW
        { 0x0141, 14 }, // ZC_COUPLESTATUS
        { 0x0142, 6 }, // ZC_OPEN_EDITDLG
        { 0x0144, 23 }, // ZC_COMPASS
        { 0x0147, 39 }, // ZC_AUTORUN_SKILL
        { 0x0148, 8 }, // ZC_RESURRECTION
        { 0x014b, 27 }, // ZC_NOTIFY_MANNER_POINT_GIVEN
        { 0x014c, -1 }, // ZC_MYGUILD_BASIC_INFO
        { 0x014e, 6 }, // ZC_ACK_GUILD_MENUINTERFACE
        { 0x0152, -1 }, // (server packet table)
        { 0x0154, -1 }, // (server packet table)
        { 0x0156, -1 }, // (server packet table)
        { 0x0158, -1 }, // (server packet table)
        { 0x015e, 6 }, // ZC_ACK_DISORGANIZE_GUILD_RESULT
        { 0x0160, -1 }, // ZC_POSITION_INFO
        { 0x0162, -1 }, // ZC_GUILD_SKILLINFO
        { 0x0164, -1 }, // (server packet table)
        { 0x0166, -1 }, // ZC_POSITION_ID_NAME_INFO
        { 0x0167, 3 }, // ZC_RESULT_MAKE_GUILD
        { 0x0169, 3 }, // ZC_ACK_REQ_JOIN_GUILD
        { 0x016a, 30 }, // ZC_REQ_JOIN_GUILD
        { 0x016f, 182 }, // ZC_GUILD_NOTICE
        { 0x0171, 30 }, // ZC_REQ_ALLY_GUILD
        { 0x0173, 3 }, // ZC_ACK_REQ_ALLY_GUILD
        { 0x0174, -1 }, // (server packet table)
        { 0x0177, -1 }, // (server packet table)
        { 0x0179, 5 }, // ZC_ACK_ITEMIDENTIFY
        { 0x017b, -1 }, // (server packet table)
        { 0x017d, 7 }, // ZC_ACK_ITEMCOMPOSITION
        { 0x017f, -1 }, // ZC_GUILD_CHAT
        { 0x0181, 3 }, // ZC_ACK_REQ_HOSTILE_GUILD
        { 0x0184, 10 }, // ZC_DELETE_RELATED_GUILD
        { 0x0188, 8 }, // ZC_ACK_ITEMREFINING
        { 0x0189, 4 }, // ZC_NOTIFY_MAPINFO
        { 0x018c, 29 }, // ZC_MONSTER_INFO
        { 0x018d, -1 }, // ZC_MAKABLEITEMLIST
        { 0x018f, 8 }, // ZC_ACK_REQMAKINGITEM
        { 0x0191, 27 }, // ZC_TALKBOX_CHATCONTENTS
        { 0x0192, 24 }, // ZC_UPDATE_MAPINFO
        { 0x0196, 9 }, // sc_notick/status_change_end
        { 0x019b, 10 }, // ZC_NOTIFY_EFFECT
        { 0x019e, 2 }, // ZC_START_CAPTURE
        { 0x01a0, 3 }, // ZC_TRYCAPTURE_MONSTER
        { 0x01a2, 37 }, // ZC_PROPERTY_PET
        { 0x01a3, 7 }, // ZC_FEED_PET
        { 0x01a4, 11 }, // ZC_CHANGESTATE_PET
        { 0x01a6, -1 }, // (server packet table)
        { 0x01aa, 10 }, // ZC_PET_ACT
        { 0x01ab, 12 }, // ZC_PAR_CHANGE_USER
        { 0x01ac, 6 }, // ZC_SKILL_UPDATE
        { 0x01ad, -1 }, // ZC_MAKINGARROW_LIST
        { 0x01b0, 11 }, // ZC_NPCSPRITE_CHANGE
        { 0x01b3, 67 }, // ZC_SHOW_IMAGE
        { 0x01b9, 6 }, // ZC_DISPEL
        { 0x01c3, -1 }, // ZC_BROADCAST2
        { 0x01c9, 97 }, // graffiti_entry
        { 0x01d0, 8 }, // ZC_SPIRITS
        { 0x01d1, 14 }, // ZC_BLADESTOP
        { 0x01d2, 10 }, // ZC_COMBODELAY
        { 0x01d3, 35 }, // ZC_SOUND
        { 0x01d4, 6 }, // ZC_OPEN_EDITDLGSTR
        { 0x01d6, 4 }, // ZC_NOTIFY_MAPPROPERTY2
        { 0x01dc, -1 }, // (server packet table)
        { 0x01de, 33 }, // ZC_NOTIFY_SKILL
        { 0x01e1, 8 }, // ZC_SPIRITS2
        { 0x01e6, 26 }, // ZC_COUPLENAME
        { 0x01ea, 6 }, // ZC_CONGRATULATION
        { 0x01eb, 10 }, // ZC_NOTIFY_POSITION_TO_GUILDM
        { 0x01f0, -1 }, // (server packet table)
        { 0x01f1, -1 }, // (server packet table)
        { 0x01f4, 32 }, // ZC_REQ_EXCHANGE_ITEM
        { 0x01f5, 9 }, // ZC_ACK_EXCHANGE_ITEM
        { 0x01fc, -1 }, // (server packet table)
        { 0x01fe, 5 }, // ZC_ACK_ITEMREPAIR
        { 0x01ff, 10 }, // ZC_HIGHJUMP
        { 0x0201, -1 }, // ZC_FRIENDS_LIST
        { 0x0205, 26 }, // ZC_DIVORCE
        { 0x0206, 35 }, // ZC_FRIENDS_STATE
        { 0x020d, -1 }, // (server packet table)
        { 0x0215, 6 }, // ZC_SKILLMSG
        { 0x0219, 282 }, // ZC_BLACKSMITH_RANK
        { 0x021a, 282 }, // ZC_ALCHEMIST_RANK
        { 0x021b, 10 }, // ZC_BLACKSMITH_POINT
        { 0x021c, 10 }, // ZC_ALCHEMIST_POINT
        { 0x0221, -1 }, // ZC_NOTIFY_WEAPONITEMLIST
        { 0x0223, 10 }, // ZC_ACK_WEAPONREFINE
        { 0x0224, 10 }, // ZC_TAEKWON_POINT
        { 0x0226, 282 }, // ZC_TAEKWON_RANK
        { 0x0229, 15 }, // ZC_STATE_CHANGE
        { 0x022f, 7 }, // ZC_FEED_MER
        { 0x0230, 12 }, // ZC_CHANGESTATE_MER
        { 0x0235, -1 }, // ZC_HOSKILLINFO_LIST
        { 0x0236, 10 }, // ZC_KILLER_POINT
        { 0x0238, 282 }, // ZC_KILLER_RANK
        { 0x0239, 11 }, // ZC_HOSKILLINFO_UPDATE
        { 0x023d, -1 }, // (server packet table)
        { 0x0240, -1 }, // (server packet table)
        { 0x0242, -1 }, // (server packet table)
        { 0x0252, -1 }, // (server packet table)
        { 0x025a, -1 }, // ZC_MAKINGITEM_LIST
        { 0x027a, -1 }, // (server packet table)
        { 0x027e, -1 }, // (server packet table)
        { 0x0287, -1 }, // ZC_PC_CASH_POINT_ITEMLIST
        { 0x028a, 18 }, // ZC_NPC_SHOWEFST_UPDATE
        { 0x028b, -1 }, // (server packet table)
        { 0x0291, 4 }, // ZC_MSG
        { 0x0293, 70 }, // ZC_BOSS_INFO
        { 0x0298, 10 }, // ZC_CASH_TIME_COUNTER
        { 0x0299, 8 }, // ZC_CASH_ITEM_DELETE
        { 0x029d, -1 }, // (server packet table)
        { 0x02a0, -1 }, // (server packet table)
        { 0x02a1, -1 }, // (server packet table)
        { 0x02a3, -1 }, // (server packet table)
        { 0x02a4, -1 }, // (server packet table)
        { 0x02a6, -1 }, // (server packet table)
        { 0x02a7, -1 }, // (server packet table)
        { 0x02b1, -1 }, // (server packet table)
        { 0x02b2, -1 }, // (server packet table)
        { 0x02b5, -1 }, // (server packet table)
        { 0x02bb, 8 }, // ZC_EQUIPITEM_DAMAGED
        { 0x02bf, -1 }, // (server packet table)
        { 0x02c0, -1 }, // (server packet table)
        { 0x02c1, -1 }, // (server packet table)
        { 0x02c2, -1 }, // ZC_FORMATSTRING_MSG
        { 0x02c5, 30 }, // ZC_PARTY_JOIN_REQ_ACK
        { 0x02c6, 30 }, // ZC_PARTY_JOIN_REQ
        { 0x02c9, 3 }, // ZC_PARTY_CONFIG
        { 0x02d3, 4 }, // ZC_NOTIFY_BIND_ON_EQUIP/notify_bounditem
        { 0x02da, 3 }, // ZC_CONFIG_NOTIFY
        { 0x02dc, -1 }, // (server packet table)
        { 0x02e7, -1 }, // (server packet table)
        { 0x02eb, 13 }, // ZC_ACCEPT_ENTER/authok
        { 0x02f3, -1 }, // (server packet table)
        { 0x02f4, -1 }, // (server packet table)
        { 0x02f5, -1 }, // (server packet table)
        { 0x02f6, -1 }, // (server packet table)
        { 0x02f7, 47 }, // ZC_UPDATE_GDID
        { 0x02f8, -1 }, // (server packet table)
        { 0x02f9, -1 }, // (server packet table)
        { 0x02fa, -1 }, // (server packet table)
        { 0x02fb, -1 }, // (server packet table)
        { 0x02fc, -1 }, // (server packet table)
        { 0x02fd, -1 }, // (server packet table)
        { 0x02fe, -1 }, // (server packet table)
        { 0x02ff, -1 }, // (server packet table)
        { 0x0300, -1 }, // (server packet table)
        { 0x0301, -1 }, // (server packet table)
        { 0x0302, -1 }, // (server packet table)
        { 0x0303, -1 }, // (server packet table)
        { 0x0304, -1 }, // (server packet table)
        { 0x0305, -1 }, // (server packet table)
        { 0x0306, -1 }, // (server packet table)
        { 0x0307, -1 }, // (server packet table)
        { 0x0308, -1 }, // (server packet table)
        { 0x0309, -1 }, // (server packet table)
        { 0x030a, -1 }, // (server packet table)
        { 0x030b, -1 }, // (server packet table)
        { 0x030c, -1 }, // (server packet table)
        { 0x030d, -1 }, // (server packet table)
        { 0x030e, -1 }, // (server packet table)
        { 0x030f, -1 }, // (server packet table)
        { 0x0310, -1 }, // (server packet table)
        { 0x0311, -1 }, // (server packet table)
        { 0x0312, -1 }, // (server packet table)
        { 0x0313, -1 }, // (server packet table)
        { 0x0314, -1 }, // (server packet table)
        { 0x0315, -1 }, // (server packet table)
        { 0x0316, -1 }, // (server packet table)
        { 0x0317, -1 }, // (server packet table)
        { 0x0318, -1 }, // (server packet table)
        { 0x0319, -1 }, // (server packet table)
        { 0x031a, -1 }, // (server packet table)
        { 0x031b, -1 }, // (server packet table)
        { 0x031c, -1 }, // (server packet table)
        { 0x031d, -1 }, // (server packet table)
        { 0x031e, -1 }, // (server packet table)
        { 0x031f, -1 }, // (server packet table)
        { 0x0320, -1 }, // (server packet table)
        { 0x0321, -1 }, // (server packet table)
        { 0x0322, -1 }, // (server packet table)
        { 0x0323, -1 }, // (server packet table)
        { 0x0324, -1 }, // (server packet table)
        { 0x0325, -1 }, // (server packet table)
        { 0x0326, -1 }, // (server packet table)
        { 0x0327, -1 }, // (server packet table)
        { 0x0328, -1 }, // (server packet table)
        { 0x0329, -1 }, // (server packet table)
        { 0x032a, -1 }, // (server packet table)
        { 0x032b, -1 }, // (server packet table)
        { 0x032c, -1 }, // (server packet table)
        { 0x032d, -1 }, // (server packet table)
        { 0x032e, -1 }, // (server packet table)
        { 0x032f, -1 }, // (server packet table)
        { 0x0330, -1 }, // (server packet table)
        { 0x0331, -1 }, // (server packet table)
        { 0x0332, -1 }, // (server packet table)
        { 0x0333, -1 }, // (server packet table)
        { 0x0334, -1 }, // (server packet table)
        { 0x0335, -1 }, // (server packet table)
        { 0x0336, -1 }, // (server packet table)
        { 0x0337, -1 }, // (server packet table)
        { 0x0338, -1 }, // (server packet table)
        { 0x0339, -1 }, // (server packet table)
        { 0x033a, -1 }, // (server packet table)
        { 0x033b, -1 }, // (server packet table)
        { 0x033c, -1 }, // (server packet table)
        { 0x033d, -1 }, // (server packet table)
        { 0x033e, -1 }, // (server packet table)
        { 0x033f, -1 }, // (server packet table)
        { 0x0340, -1 }, // (server packet table)
        { 0x0341, -1 }, // (server packet table)
        { 0x0342, -1 }, // (server packet table)
        { 0x0343, -1 }, // (server packet table)
        { 0x0344, -1 }, // (server packet table)
        { 0x0345, -1 }, // (server packet table)
        { 0x0346, -1 }, // (server packet table)
        { 0x0347, -1 }, // (server packet table)
        { 0x0348, -1 }, // (server packet table)
        { 0x0349, -1 }, // (server packet table)
        { 0x034a, -1 }, // (server packet table)
        { 0x034b, -1 }, // (server packet table)
        { 0x034c, -1 }, // (server packet table)
        { 0x034d, -1 }, // (server packet table)
        { 0x034e, -1 }, // (server packet table)
        { 0x034f, -1 }, // (server packet table)
        { 0x0350, -1 }, // (server packet table)
        { 0x0351, -1 }, // (server packet table)
        { 0x0352, -1 }, // (server packet table)
        { 0x0353, -1 }, // (server packet table)
        { 0x0354, -1 }, // (server packet table)
        { 0x0355, -1 }, // (server packet table)
        { 0x0356, -1 }, // (server packet table)
        { 0x0357, -1 }, // (server packet table)
        { 0x0358, -1 }, // (server packet table)
        { 0x0359, -1 }, // (server packet table)
        { 0x035a, -1 }, // (server packet table)
        { 0x035b, -1 }, // (server packet table)
        { 0x035d, -1 }, // (server packet table)
        { 0x0389, -1 }, // (server packet table)
        { 0x040c, -1 }, // (server packet table)
        { 0x040d, -1 }, // (server packet table)
        { 0x040e, -1 }, // (server packet table)
        { 0x040f, -1 }, // (server packet table)
        { 0x0410, -1 }, // (server packet table)
        { 0x0411, -1 }, // (server packet table)
        { 0x0412, -1 }, // (server packet table)
        { 0x0413, -1 }, // (server packet table)
        { 0x0414, -1 }, // (server packet table)
        { 0x0415, -1 }, // (server packet table)
        { 0x0416, -1 }, // (server packet table)
        { 0x0417, -1 }, // (server packet table)
        { 0x0418, -1 }, // (server packet table)
        { 0x0419, -1 }, // (server packet table)
        { 0x041a, -1 }, // (server packet table)
        { 0x041b, -1 }, // (server packet table)
        { 0x041c, -1 }, // (server packet table)
        { 0x041d, -1 }, // (server packet table)
        { 0x041e, -1 }, // (server packet table)
        { 0x041f, -1 }, // (server packet table)
        { 0x0420, -1 }, // (server packet table)
        { 0x0421, -1 }, // (server packet table)
        { 0x0422, -1 }, // (server packet table)
        { 0x0423, -1 }, // (server packet table)
        { 0x0424, -1 }, // (server packet table)
        { 0x0425, -1 }, // (server packet table)
        { 0x0426, -1 }, // (server packet table)
        { 0x0427, -1 }, // (server packet table)
        { 0x0428, -1 }, // (server packet table)
        { 0x0429, -1 }, // (server packet table)
        { 0x042a, -1 }, // (server packet table)
        { 0x042b, -1 }, // (server packet table)
        { 0x042c, -1 }, // (server packet table)
        { 0x042d, -1 }, // (server packet table)
        { 0x042e, -1 }, // (server packet table)
        { 0x042f, -1 }, // (server packet table)
        { 0x0430, -1 }, // (server packet table)
        { 0x0431, -1 }, // (server packet table)
        { 0x0432, -1 }, // (server packet table)
        { 0x0433, -1 }, // (server packet table)
        { 0x0434, -1 }, // (server packet table)
        { 0x0435, -1 }, // (server packet table)
        { 0x043d, 8 }, // ZC_SKILL_POSTDELAY
        { 0x043e, -1 }, // (server packet table)
        { 0x043f, 25 }, // status_change2
        { 0x0440, 10 }, // ZC_MILLENNIUMSHIELD
        { 0x0441, 4 }, // ZC_SKILLINFO_DELETE
        { 0x0442, -1 }, // ZC_SKILL_SELECT_REQUEST
        { 0x0444, -1 }, // (server packet table)
        { 0x0448, -1 }, // (server packet table)
        { 0x07e1, 15 }, // ZC_SKILLINFO_UPDATE2
        { 0x07e2, 8 }, // ZC_MSG_VALUE
        { 0x07e6, 8 }, // ZC_MSG_SKILL
        { 0x07e8, -1 }, // (server packet table)
        { 0x07f7, -1 }, // (server packet table)
        { 0x07f8, -1 }, // (server packet table)
        { 0x07f9, -1 }, // (server packet table)
        { 0x07fa, 8 }, // ZC_DELETE_ITEM_FROM_BODY
        { 0x07fd, -1 }, // item_drop_announce
        { 0x0805, -1 }, // (server packet table)
        { 0x080e, 14 }, // ZC_NOTIFY_HP_TO_GROUPM
        { 0x0813, -1 }, // ZC_MYITEMLIST_BUYING_STORE
        { 0x0814, 86 }, // ZC_BUYING_STORE_ENTRY
        { 0x0816, 6 }, // ZC_DISAPPEAR_BUYING_STORE_ENTRY
        { 0x0818, -1 }, // ZC_ACK_ITEMLIST_BUYING_STORE
        { 0x081e, 8 }, // ZC_EL_PAR_CHANGE
        { 0x0824, 8 }, // ZC_FAILED_TRADE_BUYING_STORE_TO_SELLER
        { 0x0837, 3 }, // ZC_SEARCH_STORE_INFO_FAILED
        { 0x083a, 5 }, // ZC_OPEN_SEARCH_STORE_INFO
        { 0x083d, 6 }, // ZC_SSILIST_ITEM_CLICK_ACK
        { 0x0849, 16 }, // ZC_SE_PC_BUY_CASHITEM_RESULT
        { 0x0856, -1 }, // (server packet table)
        { 0x0857, -1 }, // (server packet table)
        { 0x0858, -1 }, // (server packet table)
        { 0x08b3, -1 }, // (server packet table)
        { 0x08c0, -1 }, // ZC_ACK_SE_CASH_ITEM_LIST2
        { 0x08c8, 34 }, // ZC_NOTIFY_ACT/damage
        { 0x08ca, -1 }, // ZC_ACK_SCHEDULER_CASHITEM
        { 0x08cf, 10 }, // ZC_SPIRITS_ATTRIBUTE
        { 0x08d6, 6 }, // ZC_CLEAR_DIALOG/script_clear
        { 0x08d8, 27 }, // bgqueue_ack
        { 0x08d9, 30 }, // bgqueue_notify_entry
        { 0x08db, 27 }, // bgqueue_notice_delete
        { 0x08df, 50 }, // bgqueue_battlebegins
        { 0x08e8, -1 }, // (server packet table)
        { 0x08f3, -1 }, // (server packet table)
        { 0x08f5, -1 }, // (server packet table)
        { 0x08fe, -1 }, // (server packet table)
        { 0x0908, 5 }, // ZC_INVENTORY_TAB
        { 0x090e, 2 }, // ZC_ENTRY_QUEUE_INIT
        { 0x090f, -1 }, // (server packet table)
        { 0x0914, -1 }, // (server packet table)
        { 0x0915, -1 }, // (server packet table)
        { 0x096d, -1 }, // ZC_MERGE_ITEM_OPEN
        { 0x096f, 7 }, // ZC_ACK_MERGE_ITEM
        { 0x0972, -1 }, // ZC_SAY_DIALOG2
        { 0x0973, 7 }, // ZC_WAIT_DIALOG2
        { 0x097a, -1 }, // (server packet table)
        { 0x097b, 16 }, // ZC_PERSONAL_INFOMATION
        { 0x097d, 288 }, // ZC_ACK_RANKING
        { 0x097e, 12 }, // ZC_UPDATE_RANKING_POINT
        { 0x097f, -1 }, // (server packet table)
        { 0x0983, 29 }, // status_change
        { 0x0984, 28 }, // ZC_EFST_SET_ENTER
        { 0x0988, 6 }, // ZC_NOTIFY_CLAN_CONNECTINFO
        { 0x0989, 2 }, // ZC_ACK_CLAN_LEAVE
        { 0x098a, -1 }, // ZC_CLANINFO
        { 0x098e, -1 }, // ZC_NOTIFY_CLAN_CHAT
        { 0x0999, 11 }, // ZC_REQ_WEAR_EQUIP_ACK
        { 0x099a, 9 }, // ZC_REQ_TAKEOFF_EQUIP_ACK
        { 0x099b, 8 }, // maptypeproperty2
        { 0x09a6, 12 }, // ZC_BANKING_CHECK/banking_check
        { 0x09a8, 16 }, // ZC_ACK_BANKING_DEPOSIT/banking_deposit_ack
        { 0x09aa, 16 }, // ZC_ACK_BANKING_WITHDRAW/banking_withdraw_ack
        { 0x09b2, 10 }, // ZC_NOTIFY_BARGAIN_SALE_SELLING
        { 0x09b3, 6 }, // ZC_NOTIFY_BARGAIN_SALE_CLOSE
        { 0x09b7, 4 }, // ZC_ACK_OPEN_BANKING
        { 0x09b9, 4 }, // ZC_ACK_CLOSE_BANKING
        { 0x09c1, 10 }, // ZC_C_MARKERINFO
        { 0x09c4, 10 }, // ZC_ACK_COUNT_BARGAIN_SALE_ITEM
        { 0x09ca, -1 }, // skill_entry
        { 0x09cb, 17 }, // ZC_USE_SKILL
        { 0x09cd, 8 }, // ZC_MSG_COLOR
        { 0x09d7, -1 }, // (server packet table)
        { 0x09da, -1 }, // ZC_ACK_GUILDSTORAGE_LOG
        { 0x09db, -1 }, // (server packet table)
        { 0x09dc, -1 }, // (server packet table)
        { 0x09dd, -1 }, // (server packet table)
        { 0x09de, -1 }, // ZC_WHISPER
        { 0x09df, 7 }, // ZC_ACK_WHISPER
        { 0x09e5, 18 }, // ZC_DELETEITEM_FROM_MCSTORE
        { 0x09f0, -1 }, // (server packet table)
        { 0x09f8, -1 }, // (server packet table)
        { 0x09fa, -1 }, // (server packet table)
        { 0x09fd, -1 }, // unit_walking
        { 0x09fe, -1 }, // spawn_unit
        { 0x09ff, -1 }, // idle_unit
        { 0x0a02, 4 }, // ZC_DRESSROOM_OPEN
        { 0x0a0e, 14 }, // ZC_BATTLEFIELD_NOTIFY_HP
        { 0x0a15, 12 }, // ZC_GOLDPCCAFE_POINT
        { 0x0a17, 6 }, // ZC_DYNAMICNPC_CREATE_RESULT
        { 0x0a1c, -1 }, // (server packet table)
        { 0x0a1e, 3 }, // ZC_ACK_CLOSE_ROULETTE
        { 0x0a23, -1 }, // (server packet table)
        { 0x0a27, 8 }, // ZC_RECOVERY
        { 0x0a28, 3 }, // ZC_ACK_OPENSTORE2
        { 0x0a30, 106 }, // ZC_ACK_REQNAMEALL
        { 0x0a38, 3 }, // ZC_UI_OPEN0
        { 0x0a3b, -1 }, // ZC_EQUIPMENT_EFFECT
        { 0x0a3f, 11 }, // ZC_UPDATE_CARDSLOT
        { 0x0a44, -1 }, // (server packet table)
        { 0x0a47, 3 }, // ZC_STYLE_CHANGE_RES
        { 0x0a4e, 6 }, // ZC_RANDOM_COMBINE_ITEM_UI_OPEN
        { 0x0a50, 4 }, // ZC_ACK_RANDOM_COMBINE_ITEM
        { 0x0a51, 34 }, // ZC_CHECKNAME
        { 0x0a53, 10 }, // ZC_ACK_UPLOAD_MACRO_DETECTOR
        { 0x0a55, 2 }, // ZC_COMPLETE_UPLOAD_MACRO_DETECTOR_CAPTCHA
        { 0x0a57, 6 }, // ZC_ACK_APPLY_MACRO_DETECTOR
        { 0x0a58, 8 }, // ZC_APPLY_MACRO_DETECTOR
        { 0x0a59, -1 }, // ZC_APPLY_MACRO_DETECTOR_CAPTCHA
        { 0x0a5b, 7 }, // ZC_REQ_ANSWER_MACRO_DETECTOR
        { 0x0a5d, 6 }, // ZC_CLOSE_MACRO_DETECTOR
        { 0x0a6a, 12 }, // ZC_ACK_PREVIEW_MACRO_DETECTOR
        { 0x0a6b, -1 }, // ZC_PREVIEW_MACRO_DETECTOR_CAPTCHA
        { 0x0a6d, -1 }, // ZC_ACK_PLAYER_AID_IN_RANGE
        { 0x0a78, 15 }, // ZC_VIEW_CAMERAINFO
        { 0x0a7d, -1 }, // (server packet table)
        { 0x0a7e, -1 }, // ZC_STALL_VENDING_UI_OPEN
        { 0x0a81, 4 }, // ZC_STALL_UI_CLOSE
        { 0x0a91, -1 }, // ZC_STALL_BUYING_LIST_REQUEST
        { 0x0a93, 3 }, // ZC_STALL_BUYING_UI_OPEN
        { 0x0a9b, -1 }, // (server packet table)
        { 0x0aa0, 2 }, // ZC_OPEN_REFINING_UI
        { 0x0aa2, -1 }, // ZC_REFINING_MATERIAL_LIST
        { 0x0aa5, -1 }, // (server packet table)
        { 0x0aa7, 6 }, // ZC_MOVE_ITEM_FAILED
        { 0x0ab2, 7 }, // ZC_GROUP_ISALIVE
        { 0x0ab4, 6 }, // ZC_RANDOM_UPGRADE_ITEM_UI_OPEN
        { 0x0ab7, 4 }, // ZC_ACK_RANDOM_UPGRADE_ITEM
        { 0x0abd, 10 }, // ZC_NOTIFY_MEMBERINFO_TO_GROUPM
        { 0x0abe, -1 }, // ZC_WARPLIST
        { 0x0ac7, 156 }, // ZC_NPCACK_SERVERMOVE
        { 0x0acb, 12 }, // ZC_LONGLONGPAR_CHANGE
        { 0x0ada, 32 }, // ZC_BROADCAST_ITEMREFINING_RESULT
        { 0x0adb, -1 }, // ZC_DEBUGMSG
        { 0x0add, 24 }, // dropflooritem
        { 0x0adf, 58 }, // ZC_ACK_REQNAMEALL_NPC
        { 0x0ae2, 7 }, // ZC_UI_OPEN
        { 0x0ae7, 38 }, // ZC_ADVENTURER_AGENCY_JOIN_REQ/ZC_PARTY_REQ_MASTER_TO_JOIN
        { 0x0af6, 88 }, // ZC_ACK_RANKING2
        { 0x0af7, 32 }, // ZC_ACK_REQNAME_BYGID
        { 0x0afa, 58 }, // ZC_ADVENTURER_AGENCY_JOIN_RESULT/ZC_PARTY_JOIN_REQ_ACK_FROM_MASTER
        { 0x0afb, -1 }, // ZC_AUTOSPELLLIST
        { 0x0afd, -1 }, // ZC_GUILD_POSITION
        { 0x0b05, 63 }, // ZC_STALL_CHAR_DETAILS
        { 0x0b08, -1 }, // ZC_INVENTORY_START
        { 0x0b09, -1 }, // (server packet table)
        { 0x0b0b, 4 }, // ZC_INVENTORY_END
        { 0x0b0d, 10 }, // ZC_REMOVE_EFFECT
        { 0x0b15, 7 }, // ZC_ACK_OPEN_MSGBOX_EXTEND_BODYITEM_SIZE
        { 0x0b17, 3 }, // ZC_ACK_EXTEND_BODYITEM_SIZE
        { 0x0b18, 4 }, // ZC_EXTEND_BODYITEM_SIZE
        { 0x0b1a, 29 }, // ZC_USESKILL_ACK
        { 0x0b1b, 2 }, // ZC_NOTIFY_ACTORINIT
        { 0x0b1d, 2 }, // ZC_PING_LIVE
        { 0x0b20, 271 }, // ZC_SHORTCUT_KEY_LIST
        { 0x0b27, -1 }, // ZC_GUILD_AGIT_INFO
        { 0x0b2d, 11 }, // ZC_REQ_ACK_AGIT_INVESTMENT
        { 0x0b2e, 4 }, // ZC_REQ_ACK_MOVE_GUILD_AGIT
        { 0x0b36, -1 }, // ZC_GUILD_EMBLEM_IMG
        { 0x0b37, -1 }, // ZC_EQUIPWIN_MICROSCOPE
        { 0x0b39, -1 }, // (server packet table)
        { 0x0b3d, -1 }, // ZC_PC_PURCHASE_ITEMLIST_FROMMC
        { 0x0b3f, 64 }, // ZC_ACK_ADD_ITEM_RODEX
        { 0x0b40, -1 }, // ZC_PC_PURCHASE_MYITEMLIST
        { 0x0b41, 70 }, // ZC_ITEM_PICKUP_ACK
        { 0x0b42, 62 }, // ZC_ADD_EXCHANGE_ITEM
        { 0x0b43, 48 }, // ZC_CHANGE_ITEM_OPTION
        { 0x0b44, 58 }, // ZC_ADD_ITEM_TO_STORE
        { 0x0b45, 58 }, // ZC_ADD_ITEM_TO_CART
        { 0x0b47, 14 }, // ZC_CHANGE_GUILD
        { 0x0b49, 4 }, // ZC_ACK_APPLY_BARGAIN_SALE_ITEM
        { 0x0b4b, 4 }, // ZC_ACK_REMOVE_BARGAIN_SALE_ITEM
        { 0x0b4d, -1 }, // ZC_SE_CASHSHOP_LIMITED_REQ
        { 0x0b4e, -1 }, // ZC_NPC_MARKET_PURCHASE_RESULT
        { 0x0b50, 2 }, // ZC_OPEN_BARGAIN_SALE_TOOL
        { 0x0b52, 2 }, // ZC_CLOSE_BARGAIN_SALE_TOOL
        { 0x0b54, 8 }, // ZC_ACK_CASH_BARGAIN_SALE_ITEM_INFO
        { 0x0b5a, -1 }, // ZC_GRADE_ENCHANT_MATERIAL_LIST
        { 0x0b5d, 10 }, // ZC_GRADE_ENCHANT_ACK
        { 0x0b5e, 33 }, // ZC_GRADE_ENCHANT_BROADCAST_RESULT
        { 0x0b62, -1 }, // ZC_STALL_VENDING_LIST_REQUEST
        { 0x0b63, -1 }, // ZC_ACK_READ_RODEX
        { 0x0b64, -1 }, // ZC_SEARCH_STORE_INFO_ACK
        { 0x0b65, -1 }, // ZC_REPAIRITEMLIST
        { 0x0b67, 33 }, // ZC_ITEM_PICKUP_PARTY
        { 0x0b68, 12 }, // ZC_TARGET_SPIRITS
        { 0x0b69, 18 }, // ZC_NOTIFY_EFFECT3
        { 0x0b6b, 14 }, // ZC_SUMMON_HP_INIT
        { 0x0b6c, 12 }, // ZC_SUMMON_HP_UPDATE
        { 0x0b6e, 14 }, // ZC_SE_CASHSHOP_OPEN
        { 0x0b73, 8 }, // ZC_SOULENERGY
        { 0x0b77, -1 }, // ZC_PC_PURCHASE_ITEMLIST
        { 0x0b78, -1 }, // ZC_NPC_BARTER_MARKET_ITEMINFO
        { 0x0b79, -1 }, // ZC_NPC_EXPANDED_BARTER_MARKET_ITEMINFO
        { 0x0b7a, -1 }, // ZC_NPC_MARKET_OPEN
        { 0x0b7b, 118 }, // ZC_GUILD_INFO
        { 0x0b7c, -1 }, // ZC_BAN_LIST
        { 0x0b7d, -1 }, // ZC_MEMBERMGR_INFO
        { 0x0b8c, -1 }, // ZC_PLAY_NPC_BGM
        { 0x0b8d, -1 }, // ZC_REPUTE_INFO
        { 0x0b8f, 6 }, // ZC_OPEN_REFORM_UI
        { 0x0b92, 5 }, // ZC_ITEM_REFORM_ACK
        { 0x0b9a, 11 }, // ZC_UI_OPEN2/ZC_UI_OPEN_V3
        { 0x0b9f, 10 }, // ZC_RESPONSE_ENCHANT
        { 0x0ba1, 3 }, // ZC_DIALOG_TEXT_ALIGN
        { 0x0ba2, 10 }, // ZC_DIALOG_WINDOW_SIZE
        { 0x0ba3, 10 }, // ZC_DIALOG_WINDOW_POS
        { 0x0ba4, 85 }, // ZC_PROPERTY_HOMUN
        { 0x0ba5, 12 }, // ZC_HO_PAR_CHANGE
        { 0x0bae, 3 }, // ZC_ACK_TAKEOFF_EQUIP_ALL
        { 0x0bb5, 10 }, // ZC_DIALOG_WINDOW_POS2
        { 0x0bba, -1 }, // ZC_BROADCASTING_SPECIAL_ITEM_OBTAIN_item
        { 0x0bbe, 6 }, // ZC_SPECIALPOPUP
        { 0x0bcc, -1 }, // ZC_BOOK_INFO_RUNE
        { 0x0bcd, -1 }, // ZC_SET_INFO_RUNE
        { 0x0bcf, 9 }, // ZC_BOOK_RESULT_RUNE
        { 0x0bd1, 13 }, // ZC_SET_RESULT_RUNE
        { 0x0bd3, 13 }, // ZC_SET_RESULT_RUNE2
        { 0x0bd5, 9 }, // ZC_REFRESH_ENABLE_RUNE2
        { 0x0bd7, 9 }, // ZC_REFRESH_ENABLE_RUNE
        { 0x0bd9, 51 }, // ZC_RESULT_RUNE_DECOMPO
        { 0x0bde, -1 }, // (server packet table)
        { 0x0bdf, 3 }, // ZC_OPEN_RUNE_UI
        { 0x0be3, 34 }, // ZC_MACRO_USER_REPORT_RES
        { 0x0bea, 10 }, // ZC_RECEIVE_EMOTE
        { 0x0beb, 7 }, // ZC_ADDTOBUYLIST_EMOTE
        { 0x0bed, 7 }, // ZC_BUY_RESULT_EMOTE
        { 0x0bee, 5 }, // ZC_MESSAGE_EMOTE
        { 0x0bf2, 13 }, // ZC_ONLOG_ENABLE_RUNE
        { 0x0bf6, -1 }, // ZC_LIST_EMOTE
        { 0x0c0c, 4 }, // ZC_GM_CHECKER
        { 0x0c15, -1 }, // ZC_REWARD_INFO_RUNE
        { 0x0c17, 10 }, // ZC_RUNE_RESULT_REWARD
    };
}
