using System.Collections.Generic;

public static partial class StatusIconTable {

    /// <summary>
    /// Icons of the older statuses, which the client executable hardcodes instead of listing them in
    /// stateiconimginfo.lub. File names under data/texture/effect, taken from roBrowser's
    /// DB/Status/StatusInfo.js (the Korean ones are the GRF's CP949 names).
    /// </summary>
    private static readonly Dictionary<int, string> ClassicIcons = new Dictionary<int, string> {
        { 0, "프로보크.tga" }, // PROVOKE
        { 1, "인듀어.tga" }, // ENDURE
        { 2, "투핸드퀴큰.tga" }, // TWOHANDQUICKEN
        { 3, "집중력향상.tga" }, // CONCENTRATION
        { 4, "하이딩.tga" }, // HIDING
        { 5, "클로킹.tga" }, // CLOAKING
        { 6, "인찬트포이즌.tga" }, // ENCHANTPOISON
        { 7, "포이즌리액트.tga" }, // POISONREACT
        { 8, "콰그마이어.tga" }, // QUAGMIRE
        { 9, "안젤루스.tga" }, // ANGELUS
        { 10, "블레싱.tga" }, // BLESSING
        { 11, "시그넘크루시스.tga" }, // CRUCIS
        { 12, "민첩성증가.tga" }, // INC_AGI
        { 13, "민첩성감소.tga" }, // DEC_AGI
        { 14, "슬로우포이즌.tga" }, // SLOWPOISON
        { 15, "임포시티오마누스.tga" }, // IMPOSITIO
        { 16, "수줍은하루의우울.tga" }, // SUFFRAGIUM
        { 17, "아스페르시오.tga" }, // ASPERSIO
        { 18, "성체강복.tga" }, // BENEDICTIO
        { 19, "기리에엘레이손.tga" }, // KYRIE
        { 20, "마니피캇.tga" }, // MAGNIFICAT
        { 21, "글로리아.tga" }, // GLORIA
        { 22, "렉스에테르나.tga" }, // LEXAETERNA
        { 23, "아드레날린러쉬.tga" }, // ADRENALINE
        { 24, "웨폰퍼펙션.tga" }, // WEAPONPERFECT
        { 25, "오버트러스트.tga" }, // OVERTHRUST
        { 26, "맥시마이즈파워.tga" }, // MAXIMIZE
        { 27, "라이딩.tga" }, // RIDING
        { 28, "팔콘.tga" }, // FALCON
        { 29, "죽은척하기.tga" }, // TRICKDEAD
        { 30, "고성지르기.tga" }, // SHOUT
        { 31, "에너지코트.tga" }, // ENERGYCOAT
        { 32, "갑옷파괴.tga" }, // BROKENARMOR
        { 33, "무기파괴.tga" }, // BROKENWEAPON
        { 34, "환각.tga" }, // ILLUSION
        { 35, "무게50이상.tga" }, // WEIGHTOVER50
        { 36, "무게90이상.tga" }, // WEIGHTOVER90
        { 37, "공속물약.tga" }, // ATTHASTE_POTION1
        { 38, "공속물약.tga" }, // ATTHASTE_POTION2
        { 39, "공속물약.tga" }, // ATTHASTE_POTION3
        { 41, "민첩성증가.tga" }, // MOVHASTE_POTION
        { 42, "민첩성증가.tga" }, // MOVHASTE_INFINITY
        { 50, "스트립웨폰.tga" }, // NOEQUIPWEAPON
        { 51, "스트립쉴드.tga" }, // NOEQUIPSHIELD
        { 52, "스트립아머.tga" }, // NOEQUIPARMOR
        { 53, "스트립헬름.tga" }, // NOEQUIPHELM
        { 54, "케미컬프로텍션[웨폰].tga" }, // PROTECTWEAPON
        { 55, "케미컬프로텍션[쉴드].tga" }, // PROTECTSHIELD
        { 56, "케미컬프로텍션[아머].tga" }, // PROTECTARMOR
        { 57, "케미컬프로텍션[헬름].tga" }, // PROTECTHELM
        { 58, "오토가드.tga" }, // AUTOGUARD
        { 59, "리플렉트쉴드.tga" }, // REFLECTSHIELD
        { 60, "헌신.tga" }, // DEVOTION
        { 61, "신의뜻.tga" }, // PROVIDENCE
        { 62, "디펜더.tga" }, // DEFENDER
        { 64, "연마제.tga" }, // WEAPONPROPERTY
        { 65, "오토스펠.tga" }, // AUTOSPELL
        { 68, "스피어퀴큰.tga" }, // SPEARQUICKEN
        { 69, "바드노래.tga" }, // BDPLAYING
        { 87, "steelbody.tga" }, // STEELBODY
        { 88, "extremityfist.tga" }, // EXTREMITYFIST
        { 90, "프레임런쳐.tga" }, // PROPERTYFIRE
        { 91, "프로스트웨폰.tga" }, // PROPERTYWATER
        { 92, "라이트닝로더.tga" }, // PROPERTYWIND
        { 93, "사이즈믹웨폰.tga" }, // PROPERTYGROUND
        { 97, "bd_undead.tga" }, // PROPERTYUNDEAD
        { 104, "icon10.tga" }, // PARRYING
        { 106, "icon08.tga" }, // TENSIONRELAX
        { 110, "icon05.tga" }, // ASSUMPTIO
        { 112, "i_장판.tga" }, // GROUNDMAGIC
        { 114, "i_치독.tga" }, // EDP
        { 115, "icon09.tga" }, // TRUESIGHT
        { 116, "icon06.tga" }, // WINDWALK
        { 117, "icon03.tga" }, // MELTDOWN
        { 118, "icon07.tga" }, // CARTBOOST
        { 120, "icon04.tga" }, // SWORDREJECT
        { 121, "icon01.tga" }, // MARIONETTE_MASTER
        { 122, "icon01.tga" }, // MARIONETTE
        { 124, "출혈상태.tga" }, // BLOODING
        { 125, "관절공격.tga" }, // JOINTBEAT
        { 130, "엄마아빠사랑해요.tga" }, // PROTECTEXP
        { 132, "금강불괴.tga" }, // AUTOBERSERK
        { 133, "i_run.tga" }, // RUN
        { 135, "i_stormkick.tga" }, // STORMKICK_ON
        { 137, "i_downkick.tga" }, // DOWNKICK_ON
        { 139, "i_turnkick.tga" }, // TURNKICK_ON
        { 141, "i_counter.tga" }, // COUNTER_ON
        { 143, "i_dodge.tga" }, // DODGE_ON
        { 145, "i_run.tga" }, // STRUP
        { 146, "캐시갑옷속성부여.tga" }, // PROPERTYDARK
        { 147, "아드레날린러쉬.tga" }, // ADRENALINE2
        { 148, "i_p_tele.tga" }, // PROPERTYTELEKINESIS
        { 150, "plusattackpower.tga" }, // PLUSATTACKPOWER
        { 151, "plusmagicpower.tga" }, // PLUSMAGICPOWER
        { 156, "i_kaizel.tga" }, // KAIZEL
        { 157, "i_kaahi.tga" }, // KAAHI
        { 158, "i_kaupe.tga" }, // KAUPE
        { 161, "i_onehand.tga" }, // ONEHANDQUICKEN
        { 169, "i_suncomfort.tga" }, // SUN_COMFORT
        { 170, "i_mooncomfort.tga" }, // MOON_COMFORT
        { 171, "i_starcomfort.tga" }, // STAR_COMFORT
        { 181, "i_프리저브.tga" }, // PRESERVE
        { 182, "i_체이스힘.tga" }, // CHASEWALK2
        { 186, "i_더블캐스팅.tga" }, // DOUBLECASTING
        { 188, "i_오버맥스.tga" }, // OVERTHRUSTMAX
        { 191, "i_타로카드.tga" }, // TAROTCARD
        { 197, "i_shrink.tga" }, // CR_SHRINK
        { 198, "i_sightblaster.tga" }, // WZ_SIGHTBLASTER
        { 200, "i_closeconfine.tga" }, // RG_CCONFINE_M
        { 201, "i_closeconfine.tga" }, // RG_CCONFINE_S
        { 203, "i_madness.tga" }, // GS_MADNESSCANCEL
        { 204, "i_fever.tga" }, // GS_GATLINGFEVER
        { 205, "글로리아.tga" }, // EARTHSCROLL
        { 206, "i_maemi.tga" }, // NJ_UTSUSEMI
        { 207, "i_bunsin.tga" }, // NJ_BUNSINJYUTSU
        { 208, "i_nen.tga" }, // NJ_NEN
        { 209, "i_adjustment.tga" }, // GS_ADJUSTMENT
        { 210, "i_accuracy.tga" }, // GS_ACCURACY
        { 217, "라이딩.tga" }, // GRIFFON
        { 241, "str_gogi.tga" }, // FOOD_STR
        { 242, "agi_gogi.tga" }, // FOOD_AGI
        { 243, "vit_gogi.tga" }, // FOOD_VIT
        { 244, "dex_gogi.tga" }, // FOOD_DEX
        { 245, "int_gogi.tga" }, // FOOD_INT
        { 246, "luk_gogi.tga" }, // FOOD_LUK
        { 247, "gogi.tga" }, // FOOD_BASICAVOIDANCE
        { 248, "gogi.tga" }, // FOOD_BASICHIT
        { 249, "gogi.tga" }, // FOOD_CRITICALSUCCESSVALUE
        { 250, "exp.tga" }, // CASH_PLUSEXP
        { 251, "death.tga" }, // CASH_DEATHPENALTY
        { 252, "item.tga" }, // CASH_RECEIVEITEM
        { 271, "str_gogi.tga" }, // FOOD_STR_CASH
        { 272, "agi_gogi.tga" }, // FOOD_AGI_CASH
        { 273, "vit_gogi.tga" }, // FOOD_VIT_CASH
        { 274, "dex_gogi.tga" }, // FOOD_DEX_CASH
        { 275, "int_gogi.tga" }, // FOOD_INT_CASH
        { 276, "luk_gogi.tga" }, // FOOD_LUK_CASH
        { 282, "slowcast.tga" }, // SLOWCAST
        { 286, "criticalwound.tga" }, // CRITICALWOUND
        { 289, "민첩성증가.tga" }, // MOVHASTE_HORSE
        { 290, "gogi.tga" }, // PROTECT_DEF
        { 291, "마법방어포션.tga" }, // PROTECT_MDEF
        { 292, "중형생명수.tga" }, // HEALPLUS
        { 293, "소형생명수.tga" }, // S_LIFEPOTION
        { 294, "중형생명수.tga" }, // L_LIFEPOTION
        { 295, "스트라이킹.tga" }, // CRITICALPERCENT
        { 298, "plusmagicpower.tga" }, // TARGET_ASPD
        { 301, "소형생명수.tga" }, // TARGET_BLOOD
        { 302, "캐시갑옷속성부여.tga" }, // ARMOR_PROPERTY
        { 304, "npc_hellpower.tga" }, // HELLPOWER
        { 312, "job.tga" }, // CASH_PLUSONLYJOBEXP
        { 313, "icon06.tga" }, // PARTYFLEE
        { 314, "death.tga" }, // ANGEL_PROTECT
        { 316, "rk_enchant.tga" }, // ENCHANTBLADE
        { 318, "rk_nauthiz.tga" }, // REFRESH
        { 319, "rk_turisuss.tga" }, // GIANTGROWTH
        { 320, "rk_hagalaz.tga" }, // STONEHARDSKIN
        { 321, "rk_isha.tga" }, // VITALITYACTIVATION
        { 322, "rk_eisir.tga" }, // FIGHTINGSPIRIT
        { 323, "rk_uruz.tga" }, // ABUNDANCE
        { 333, "포이즈닝웨폰.tga" }, // CLOAKINGEXCEED
        { 334, "할루시네이션워크.tga" }, // HALLUCINATIONWALK
        { 336, "레노바티오.tga" }, // RENOVATIO
        { 337, "웨폰블로킹.tga" }, // WEAPONBLOCKING
        { 341, "포이즈닝웨폰.tga" }, // POISONINGWEAPON
        { 342, "신경마비독.tga" }, // TOXIN
        { 343, "감각마비독.tga" }, // PARALYSE
        { 344, "쇠약독.tga" }, // VENOMBLEED
        { 345, "웃음버섯.tga" }, // MAGICMUSHROOM
        { 346, "상처오염독.tga" }, // DEATHHURT
        { 347, "열병독.tga" }, // PYREXIA
        { 348, "망각의재.tga" }, // OBLIVIONCURSE
        { 349, "거머리.tga" }, // LEECHESEND
        { 351, "frostmisty.tga" }, // FROSTMISTY
        { 352, "ra_fearbreeze.tga" }, // FEARBREEZE
        { 354, "marshofabyss.tga" }, // MARSHOFABYSS
        { 355, "recognizespell.tga" }, // RECOGNIZEDSPELL
        { 357, "wolfmount.tga" }, // WUGRIDER
        { 361, "엑셀레이션.tga" }, // ACCELERATION
        { 362, "호버링.tga" }, // HOVERING
        { 368, "mvpcard_taogunka.tga" }, // MVPCARD_TAOGUNKA
        { 369, "mvpcard_mistress.tga" }, // MVPCARD_MISTRESS
        { 370, "mvpcard_orchero.tga" }, // MVPCARD_ORCHERO
        { 371, "mvpcard_orclord.tga" }, // MVPCARD_ORCLORD
        { 373, "오버히트.tga" }, // OVERHEAT
        { 374, "셰이프쉬프트.tga" }, // SHAPESHIFT
        { 375, "인프라레드스캔.tga" }, // INFRAREDSCAN
        { 377, "뉴트럴배리어.tga" }, // NEUTRALBARRIER
        { 379, "스텔스필드.tga" }, // STEALTHFIELD
        { 381, "efst_atk.tga" }, // MANU_ATK
        { 382, "efst_def.tga" }, // MANU_DEF
        { 383, "efst_atk.tga" }, // SPL_ATK
        { 384, "efst_def.tga" }, // SPL_DEF
        { 385, "리프로듀스.tga" }, // REPRODUCE
        { 386, "efst_matk.tga" }, // MANU_MATK
        { 387, "efst_matk.tga" }, // SPL_MATK
        { 388, "str_gogi.tga" }, // STR_SCROLL
        { 389, "int_gogi.tga" }, // INT_SCROLL
        { 390, "lg_reflectdamage.tga" }, // LG_REFLECTDAMAGE
        { 391, "포스오브뱅가드.tga" }, // FORCEOFVANGUARD
        { 393, "오토쉐도우스펠.tga" }, // AUTOSHADOWSPELL
        { 394, "쉐도우폼.tga" }, // SHADOWFORM
        { 396, "lg_shieldspell_방.tga" }, // SHIELDSPELL_DEF
        { 397, "lg_shieldspell_마.tga" }, // SHIELDSPELL_MDEF
        { 398, "lg_shieldspell_연.tga" }, // SHIELDSPELL_REF
        { 401, "민첩성감소.tga" }, // ADORAMUS
        { 402, "lg_prestige.tga" }, // PRESTIGE
        { 403, "인비지빌리티.tga" }, // INVISIBILITY
        { 404, "데들리인펙트.tga" }, // DEADLYINFECT
        { 405, "lg_banding.tga" }, // BANDING
        { 407, "lg_inspiration.tga" }, // INSPIRATION
        { 408, "masquerade_enervation.tga" }, // ENERVATION
        { 409, "masquerade_groomy.tga" }, // GROOMY
        { 410, "잠룡승천.tga" }, // RAISINGDRAGON
        { 411, "masquerade_ignorance.tga" }, // IGNORANCE
        { 412, "masquerade_laziness.tga" }, // LAZINESS
        { 413, "icon02.tga" }, // LIGHTNINGWALK
        { 414, "공속물약.tga" }, // ACARAJE
        { 415, "masquerade_unlucky.tga" }, // UNLUCKY
        { 418, "masquerade_weakness.tga" }, // WEAKNESS
        { 419, "기리에엘레이손.tga" }, // CRESCENTELBOW
        { 421, "스트립액세서리.tga" }, // STRIPACCESSARY
        { 423, "gogi.tga" }, // POPECOOKIE
        { 425, "점혈구.tga" }, // GENTLETOUCH_ENERGYGAIN
        { 426, "점혈반.tga" }, // GENTLETOUCH_CHANGE
        { 427, "점혈활.tga" }, // GENTLETOUCH_REVITALIZE
        { 429, "스윙댄스.tga" }, // SWING
        { 430, "연인들을위한심포니.tga" }, // SYMPHONY_LOVE
        { 435, "안식의자장가.tga" }, // DEEP_SLEEP
        { 436, "순환하는자연의소리.tga" }, // SIRCLEOFNATURE
        { 437, "다이아몬드더스트.tga" }, // COLD
        { 438, "수줍은하루의우울.tga" }, // GLOOMYDAY
        { 439, "마나의노래.tga" }, // SONG_OF_MANA
        { 441, "워그와함께춤을.tga" }, // DANCE_WITH_WUG
        { 442, "풍차를향해돌격.tga" }, // RUSH_WINDMILL
        { 443, "마스커레이드.tga" }, // ECHOSONG
        { 444, "하모나이즈.tga" }, // HARMONIZE
        { 445, "스트라이킹.tga" }, // STRIKING
        { 446, "워머.tga" }, // WARMER
        { 447, "달빛의세레나데.tga" }, // MOONLIT_SERENADE
        { 448, "새터데이나이트피버.tga" }, // SATURDAY_NIGHT_FEVER
        { 450, "애널라이즈.tga" }, // ANALYZE
        { 451, "레라드의이슬.tga" }, // LERADS_DEW
        { 452, "멜로디오브싱크.tga" }, // MELODYOFSINK
        { 454, "언리미티드허밍보이스.tga" }, // UNLIMITED_HUMMING_VOICE
        { 461, "icon07.tga" }, // GN_CARTBOOST
        { 463, "가시나무덫.tga" }, // THORNS_TRAP
        { 472, "세크라멘트.tga" }, // AB_SECRAMENT
        { 473, "icon05.tga" }, // ASSUMPTIO2
        { 476, "안티매터리얼.tga" }, // STOMACHACHE
        { 491, "str_gogi.tga" }, // SAVAGE_STEAK
        { 492, "int_gogi.tga" }, // COCKTAIL_WARG_BLOOD
        { 493, "vit_gogi.tga" }, // MINOR_BBQ
        { 494, "dex_gogi.tga" }, // SIROMA_ICE_TEA
        { 495, "agi_gogi.tga" }, // DROCERA_HERB_STEAMED
        { 496, "luk_gogi.tga" }, // PUTTI_TAILS_NOODLES
        { 573, "gogi.tga" }, // MORA_BUFF
        { 577, "세라4.tga" }, // PAIN_KILLER
        { 578, "중형생명수.tga" }, // G_LIFEPOTION
        { 579, "에이라1.tga" }, // VITALIZE_POTION
        { 580, "에이라1.tga" }, // LIGHT_OF_REGENE
        { 581, "에이라2.tga" }, // OVERED_BOOST
        { 583, "all_odins_power.tga" }, // ODINS_POWER
        { 584, "efst_atk.tga" }, // STYLE_CHANGE
        { 605, "디이터1.tga" }, // MAGMA_FLOW
        { 606, "디이터2.tga" }, // GRANITIC_ARMOR
        { 607, "디이터4.tga" }, // PYROCLASTIC
        { 608, "디이터5.tga" }, // VOLCANIC_ASH
        { 611, "plusmagicpower.tga" }, // MAGIC_CANDY
        { 613, "라이딩.tga" }, // ALL_RIDING
        { 618, "item.tga" }, // OVERLAPEXPUP
        { 621, "변신.tga" }, // MONSTER_TRANSFORM
        { 622, "앉기.tga" }, // SIT
        { 636, "job.tga" }, // REWARD_PLUSONLYJOBEXP
        { 646, "meikyousisui.tga" }, // MEIKYOUSISUI
        { 647, "aspdcash.tga" }, // ATTHASTE_CASH
        { 652, "izayoi.tga" }, // IZAYOI
        { 654, "kg_kagehumi.tga" }, // KG_KAGEHUMI
        { 655, "kyomu.tga" }, // KYOMU
        { 656, "kagemusya.tga" }, // KAGEMUSYA
        { 657, "zangetsu.tga" }, // ZANGETSU
        { 659, "gensou.tga" }, // GENSOU
        { 660, "akaitsuki.tga" }, // AKAITSUKI
        { 670, "중형생명수.tga" }, // M_LIFEPOTION
        { 675, "flower_leaf.tga" }, // FLOWER_LEAF
        { 676, "all_ray_of_protection.tga" }, // RAY_OF_PROTECTION
        { 677, "glastheim_atk.tga" }, // GLASTHEIM_ATK
        { 678, "glastheim_def.tga" }, // GLASTHEIM_DEF
        { 679, "glastheim_heal.tga" }, // GLASTHEIM_HEAL
        { 695, "ArrowN.tga" }, // CLIENT_ONLY_EQUIP_ARROW
        { 715, "frigg_song.tga" }, // FRIGG_SONG
        { 720, "full_throttle.tga" }, // FULL_THROTTLE
        { 730, "darkcrow.tga" }, // DARKCROW
        { 897, "weapon_property.tga" }, // ATTACK_PROPERTY_NOTHING
        { 898, "weapon_property_water.tga" }, // ATTACK_PROPERTY_WATER
        { 899, "weapon_property_ground.tga" }, // ATTACK_PROPERTY_GROUND
        { 900, "weapon_property_fire.tga" }, // ATTACK_PROPERTY_FIRE
        { 901, "weapon_property_wind.tga" }, // ATTACK_PROPERTY_WIND
        { 902, "weapon_property.tga" }, // ATTACK_PROPERTY_POISON
        { 903, "weapon_property.tga" }, // ATTACK_PROPERTY_SAINT
        { 904, "weapon_property.tga" }, // ATTACK_PROPERTY_DARKNESS
        { 905, "weapon_property.tga" }, // ATTACK_PROPERTY_TELEKINESIS
        { 906, "weapon_property.tga" }, // ATTACK_PROPERTY_UNDEAD
        { 907, "resist_elemental_nothing.tga" }, // RESIST_PROPERTY_NOTHING
        { 908, "resist_elemental_water.tga" }, // RESIST_PROPERTY_WATER
        { 909, "resist_elemental_ground.tga" }, // RESIST_PROPERTY_GROUND
        { 910, "resist_elemental_fire.tga" }, // RESIST_PROPERTY_FIRE
        { 911, "resist_elemental_wind.tga" }, // RESIST_PROPERTY_WIND
        { 912, "resist_elemental_poison.tga" }, // RESIST_PROPERTY_POISON
        { 913, "resist_elemental_saint.tga" }, // RESIST_PROPERTY_SAINT
        { 914, "resist_elemental_darkness.tga" }, // RESIST_PROPERTY_DARKNESS
        { 915, "resist_elemental_telekinesis.tga" }, // RESIST_PROPERTY_TELEKINESIS
        { 916, "resist_elemental_undead.tga" }, // RESIST_PROPERTY_UNDEAD
    };
}
